Pick linux vs darwin bazel + platforms
This makes it so we don't try darwin only options on Linux.

Change-Id: I560497f38785d5ea7aba3da9157aa7479c8a3343
Signed-off-by: Austin Schuh <austin.linux@gmail.com>

diff --git a/tools/bazel b/tools/bazel
--- a/tools/bazel
+++ b/tools/bazel
@@ -40,7 +40,27 @@ if [[ ! -d "${DOWNLOAD_DIR}" ]]; then
   exit 1
 fi
 
-readonly INSTALLER_NAME="bazel-${VERSION}-linux-x86_64"
+OS=$(uname -s | tr '[:upper:]' '[:lower:]')
+ARCH=$(uname -m)
+case "${ARCH}" in
+  x86_64)          ARCH="x86_64" ;;
+  aarch64 | arm64) ARCH="arm64" ;;
+  *) echo "Unsupported architecture: ${ARCH}" >&2; exit 1 ;;
+esac
+
+# Explicitly check the supported platform list.
+case "${OS}-${ARCH}" in
+  "linux-x86_64")
+    ;;
+  "darwin-arm64")
+    ;;
+  *)
+    echo "Error: Platform '${OS}-${ARCH}' is not supported." >&2
+    exit 1
+    ;;
+esac
+
+readonly INSTALLER_NAME="bazel-${VERSION}-${OS}-${ARCH}"
 readonly DOWNLOAD_URL="https://realtimeroboticsgroup.org/build-dependencies/github.com/bazelbuild/bazel/releases/download/${VERSION}/${INSTALLER_NAME}"
 
 if [[ ! -d "${VERSION_DIR}" ]]; then
